### ISSUE TITLE
Webpack bundle too large

### ISSUE THREAD

**Issue by mpetrunic** [NodeFactoryIo/js-libp2p-noise#27]
- bcrypto is using "import" instead of require which pull entire bcrypto lib and adds ~1.2 Mb to webpack bundle

**Comment by mpetrunic** [comment]
https://bundlephobia.com/result?p=libp2p-noise@1.0.0-rc.9

**Comment by morrigan** [comment]
Reduced to 681kB - https://bundlephobia.com/result?p=libp2p-noise@1.1.0
Not great, not terrible.

Closing in favor that libp2p-crypto will it's reduce size.

**Comment by jacobheun** [comment]
Just FYI, I am working on downstream integration of this in js-ipfs, https://github.com/ipfs/js-ipfs/pull/3004. The bundlesize change there is only around 73KB. Not great, but not as much as I was expecting. I'll be working on this over the next few weeks and will submit any updates here as I find them.

> libp2p-crypto will it's reduce size

I am planning on making libp2p-crypto composable to make reducing the size easier, but likely won't get to that until around July.

**Comment by mpetrunic** [comment]
Would be nice if you added x25519, aead(chacha-poly) and hkdf support, we tried swapping those but none of the x25519 alternatives worked in interop.
