### ISSUE TITLE
proto/payload.json is not being included in the npm dist/lib folders

### ISSUE THREAD

**Issue by jacobheun** [NodeFactoryIo/js-libp2p-noise#29]
I have started work on integrating the most recent `libp2p-noise` RC into the js-libp2p test suite. The protobuf `payload.json` file is not being included in the bundle code and cannot be found. I checked both the `lib` and `dist` folders, neither includes the `proto` folder.

```log
Error: Cannot find module './proto/payload.json'
Require stack:
- /libp2p/node_modules/libp2p-noise/dist/utils.js
- /libp2p/node_modules/libp2p-noise/dist/handshakes/xx.js
- /libp2p/node_modules/libp2p-noise/dist/handshake-xx.js
- /libp2p/node_modules/libp2p-noise/dist/noise.js
- /libp2p/node_modules/libp2p-noise/dist/index.js
- /libp2p/test/dialing/direct.node.js
```

**Comment by mpetrunic** [comment]
I was testing it in another project and stucked on typescript types. Will fix this asap

**Comment by mpetrunic** [comment]
@jacobheun it's present in libp2p-noise@1.0.0-rc3
