### ISSUE TITLE
`performHandshake` throws if remotePeer is undefined 

### ISSUE THREAD

**Issue by jacobheun** [NodeFactoryIo/js-libp2p-noise#30]
It's possible in libp2p for the `remotePeer` to be unknown prior to encryption occurring, which is the case for all inbound connections. Currently if the remotePeer is not provided `performHandshake` and similar methods will throw an error which appears to be originating from usage of `remotePeer.id` in the KeyCache. 

I hacked around this locally by just guarding against this in `Keycache.load`, but also encountered the issue when storing, as the original `remotePeer` is used for storing. If the `remotePeer` isn't known, the handshake process should set and return it. If it is known, we should validate that the provided peer matches the verified peer from the handshake process.

**Comment by mpetrunic** [comment]
should be resolved with #32 in version 1.0.0-rc4
