### ISSUE TITLE
it-length-prefixed would welcome a PR for type definitions 😃

### ISSUE THREAD

**Issue by alanshaw** [NodeFactoryIo/js-libp2p-noise#66]
https://github.com/NodeFactoryIo/js-libp2p-noise/blob/master/src/%40types/it-length-prefixed/index.d.ts

If they're good for everyone to use I'd welcome a PR.

**Comment by mpetrunic** [comment]
Sure, exoect PR soon 🙂

**Comment by mpetrunic** [comment]
Just remembered this.
https://github.com/alanshaw/it-length-prefixed/pull/11

I don't think CI is failing because of me
