### ISSUE TITLE
Noise prologue is set to the protocol id string

### ISSUE THREAD

**Issue by yusefnapora** [NodeFactoryIo/js-libp2p-noise#8]
I noticed that the noise prologue is initialized with the ID string (`/noise`), which will cause interop issues with the go implementation, which doesn't set the prologue at all.

Ideally, both implementations would set the prologue to whatever bytes were actually exchanged over the wire prior to the noise handshake occurring. This would be the back-and-forth from multistream-select that selects Noise as the crypto channel. However, I don't think we have a good interface for providing that data in either go or js 😞 

In the long term, we're planning to move away from negotiating crypto channels entirely. Instead, the crypto protocol will be part of the multiaddr. So there won't be a need for a prologue in that case.

We could potentially update the secure transport interfaces in js and go to accept optional prologue data, but we haven't scoped that work out yet, and given that we want to move away from negotiation it may not be worth the effort. 

In the meantime, it seems best to just ditch the prologue entirely, rather than set it to a fixed string.

**Comment by mpetrunic** [comment]
@yusefnapora 
> I noticed that the noise prologue is initialized with the ID string (/noise), which will cause interop issues with the go implementation, which doesn't set the prologue at all.

Go implementation is setting prologue, but it's setting it to wrong version (according to spec):
https://github.com/ChainSafe/go-libp2p-noise/blob/master/protocol.go#L84
https://github.com/ChainSafe/go-libp2p-noise/blob/master/transport.go#L16

Spec: https://github.com/libp2p/specs/tree/master/noise#negotiation


We cannot ditch it currently, as "upgrader" in js-libp2p is using it to negotiate whether to use secio or noise to upgrade connection.

**Comment by morrigan** [comment]
Hi @yusefnapora, any new input on this?

**Comment by yusefnapora** [comment]
The protocol string is incorrect in the ChainSafe repo, but I've fixed it after pulling it into the libp2p org (see https://github.com/libp2p/go-libp2p-noise/blob/master/transport.go#L16).

But the Noise prologue is distinct from the protocol string; it's supposed to contain whatever bytes were exchanged on the wire before the Noise handshake kicks in. We don't really have a great way to get that data out of multistream-select at the moment 😞 

In the go implementation, `secureSession.prologue` is read from but never written to, so it remains an empty byte slice.

I think for now it's good enough to just set the prologue to an empty buffer & we can scope out how much work is involved in getting the actual pre-handshake negotiation data to set the prologue correctly.

**Comment by yusefnapora** [comment]
BTW, I noticed that the prologue is getting set in [`IK_test.go`](https://github.com/libp2p/go-libp2p-noise/blob/master/ik/IK_test.go#L17), which is probably confusing. But in the "production path" it's always empty.

**Comment by morrigan** [comment]
@yusefnapora ok, thanks for elaborating. Sure, let's do it that way for now.

**Comment by yusefnapora** [comment]
Hey @morrigan I just realized that I never pushed the commit that sets the prologue to the empty byte slice in go 😞 I'm sorry about that - you were totally right that go was setting it to the protocol id, but I had a memory of changing it & didn't realize that it wasn't pushed to the remote.

At any rate, didn't mean to gaslight you there 😄 - I just merged it in on the go side.

**Comment by morrigan** [comment]
> At any rate, didn't mean to gaslight you there smile - I just merged it in on the go side.

Haha, no problem, it happens! I'm glad that we are not totally crazy here :D
