### ISSUE TITLE
Buffer is not defined in browser

### ISSUE THREAD

**Issue by HexaField** [NodeFactoryIo/js-libp2p-noise#80]
The use of buffer is not provided by default in the browser environment

**Comment by mpetrunic** [comment]
Do you have some stacktraces? We think, we are using https://github.com/feross/buffer everywhere.

**Comment by HexaField** [comment]
Being minified, it's not particularly helpful 

```
index.min.js:2 Uncaught (in promise) ReferenceError: Buffer is not defined
    at Object.<anonymous> (index.min.js:2)
    at r (index.min.js:2)
    at Object.<anonymous> (index.min.js:2)
    at r (index.min.js:2)
    at Object.<anonymous> (index.min.js:2)
    at r (index.min.js:2)
    at Object.<anonymous> (index.min.js:2)
    at r (index.min.js:2)
    at Object.<anonymous> (index.min.js:2)
    at r (index.min.js:2)
```

Though I have figured out how to polyfill with feross buffer package. Unfortunately it seems a bit hacky, I'm not sure if this is the intended way to use these packages. It might be a good idea to add documentation on how to use this in the browser.

```js
await import('https://bundle.run/buffer@6.0.3')
window.Buffer = window.buffer.Buffer
await import('https://unpkg.com/libp2p-noise@2.0.1/dist/index.min.js')
```

**Comment by HexaField** [comment]
Unfortunately it seems that this solution leads to connections failing to complete, I'm not getting any errors but it just falls back to SECIO.

**Comment by mpetrunic** [comment]
I just looked into it. We ran tests in browser and they are bundled without Buffer polyfill (https://github.com/ipfs/aegir/blob/master/src/config/webpack.config.js#L133).

 I would suggest to remove minification to get troubled line or at least file. What version of noise are you using?

**Comment by HexaField** [comment]
I'm using 2.0.1

**Comment by HexaField** [comment]
I'm a bit of a nuffy. Since I do dynamic imports, I was configuring noise as

```js
await import('https://unpkg.com/libp2p-noise@2.0.1/dist/index.min.js')
// ...
connEncryption: [
    window.Libp2pNoise
]
```
and I should have been using

```js
await import('https://unpkg.com/libp2p-noise@2.0.1/dist/index.min.js')
// ...
connEncryption: [
    window.Libp2pNoise.NOISE
]
```

Hope this helps anyone in the future. It didn't throw any errors doing the former, despite no valid encryption being supplied. I'll look into adding a test & new error throw for this in https://github.com/libp2p/js-libp2p for this case.
