### ISSUE TITLE
2.0.3 is broken

### ISSUE THREAD

**Issue by ukstv** [NodeFactoryIo/js-libp2p-noise#86]
Guys, your package.json specifies "main" file to be `dist/src/index.js`. There is no such file. It basically breaks everything libp2p- or ipfs-based.

**Comment by ukstv** [comment]
FYI there is a nice `prepublishOnly` npm hook that builds before publishing.

**Comment by ukstv** [comment]
2.02 is broken too, exactly the same way.

**Comment by morrigan** [comment]
Thanks for the report! Working on it.

**Comment by mpetrunic** [comment]
> FYI there is a nice `prepublishOnly` npm hook that builds before publishing. https://docs.npmjs.com/cli/v6/using-npm/scripts#prepare-and-prepublish

Our build process is automated using github actions. It seems that latest aegir version doesn't generate .js files anymore. Trying some older versions.

**Comment by achingbrain** [comment]
cc @hugomrdias

**Comment by mpetrunic** [comment]
28.2.0 is latest that works. Gonna release libp2p-noise@2.0.4 with aegir 28.2.0 so others can use libp2p-noise again

**Comment by mpetrunic** [comment]
libp2p-noise@2.0.4 released. Tracking aegir update (because current version contains vulnerable dependency) here: https://github.com/NodeFactoryIo/js-libp2p-noise/issues/88
