### ISSUE TITLE
Noise consumes more entropy than necessary

### ISSUE THREAD

**Issue by D4nte** [NodeFactoryIo/js-libp2p-noise#91]
If my understanding is correct, due to this export https://github.com/NodeFactoryIo/js-libp2p-noise/blob/522d28cd8b850ce4cda760dc432063d2380169d6/src/index.ts#L7

The constructor is always evaluated for this call, even if a consumer chooses to use the constructor with a static key, e.g.:

```
import { Noise} from "libp2p-noise"

const noise = new Noise(privateKey, Buffer.alloc(x));
```

Which means entropy to generate a private key for the `NOISE` constant is wasted.

Would it be possible to review this strategy for a lazy approach? Or maybe remove the `NOISE` export and just let users call `new Noise()`?

**Comment by mpetrunic** [comment]
Since that would be breaking change (I think most users are using this by just importing `NOISE`), I would suggest that you import `Noise` class directly from `libp2p-noise/dist/src/noise`. If I'm not mistaken, this way, constant should not be instantiated.

Would that work for you?

**Comment by D4nte** [comment]
Ah, thanks! I tried to import from `libp2p-noise/src/noise` but it created type issues. The trick was to use to import from the `dist` folder. This resolves my issue.
